apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
  environments:
  - key: dev
    owner: abhishekghode
    repository: jx3-eks-vault
  - key: staging
  - key: production
  - gitKind: github
    gitServer: https://github.com
    key: jx3-eks-vault-4
    owner: abhishekghode
    promotionStrategy: Never
    remoteCluster: true
    repository: jx3-eks-vault-4
  ingress:
    domain: 3.108.128.6.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: bot-abhi
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
